name: CI

on:
  push:
    branches:
      - "**"
    paths:
      - "**.c"
      - ".github/workflows/ci.yaml"
      - "Makefile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mongoc
        run: sudo apt install -y libmongoc-dev

      - name: make
        run: make debug
